### ISSUE TITLE
Ask location permission

### ISSUE THREAD

**Issue by rrijal53** [treehouses/flutter-ble-terminal#43]
Bluetooth will not work if location service is disabled.
We need to implement https://pub.dev/packages/permission_handler to ask for the location and bluetooth permission for both android and IOS.

**Comment by ComputerOnFire** [comment]
looks like there's a new permission called BLUETOOTH_SCAN needed for Android 12 https://developer.android.com/guide/topics/connectivity/bluetooth/permissions?hl=sl&skip_cache=true
