### ISSUE TITLE
launching app without Bluetooth crashes scan function

### ISSUE THREAD

**Issue by ComputerOnFire** [treehouses/flutter-ble-terminal#52]
Tapping the refresh button afterwards will result in this exception
```
Handler: "onTap"
Recognizer:
  TapGestureRecognizer#fde73
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: type 'Null' is not a subtype of type 'Iterable<dynamic>'
```

Potential solution: prevent scan from happening if there is no Bluetooth connected.

**Comment by BryanGazali** [comment]
Currently, feature in place where user is notified that their Bluetooth is off and are prevented from using scan function. User thus unlikely to encounter this error.
![Screenshot_20220716-111126 1](https://user-images.githubusercontent.com/46581520/179336805-c4bc021d-75dc-4ea6-ab25-7e0ae4aa393d.jpg)
